### ISSUE TITLE
Simultaneous button press issue

### ISSUE THREAD

**Issue by chriswyatt** [soiaf/FallingBlocks#1]
When holding down left/right and the rotate key, the tetrimino will rotate every time it shifts along the grid. Ideally it would not rotate the tetrimino until the next keydown action.

**Comment by soiaf** [comment]
Thanks for the feedback!
I should have some free time in a couple of weeks and I'll see if I can make this work better.

**Comment by soiaf** [comment]
Sorry for the delay getting to this.
I've uploaded a new version of the code that prevents the piece from rotating every time it shifts along the grid when holding down the left/right key.
Hopefully this now works the way that you'd like it to, but let me know if it's not quite what you were looking for!

**Comment by chriswyatt** [comment]
Thanks.

I'll try and check out the update some time this week.

**Comment by soiaf** [comment]
I've rewritten this section of code and added a new option in the settings menu for 'simultaneous keys'. The default value is 'off'. If you enable this option on you are able to press multiple keys
during the one action e.g. move left and spin at the same time, but it would be slower than when you raised this issue (as it was spinning/moving too quickly).

**Comment by chriswyatt** [comment]
It seems to handle nicely with the option either on or off.

Keyboard controls seem fine (from my quick testing). When using the Kempston joystick (well, I lie, I'm playing with an emulator), it spins once when you keep up held down; however if you hold down or the fire button, the Tetrimino spins very quickly. I'm not sure if this is intentional or not. It's a tricky game to play with the Kempston anyway, due to only having one button on the joystick.

**Comment by soiaf** [comment]
Great! Glad I've got the issue sorted :-)

As for joystick support - yes, that's the next thing I was planning on working on. Apart from trying to make the controls work as well as they can with the joystick, I also need to modify the main menu so all the options are selectable using up/down/fire.

Thanks again for the feedback and testing!

**Comment by soiaf** [comment]
I've now improved joystick support.
You can navigate through the main menu screens using up, down and fire (if kempston joystick is detected). I've also adjusted the in-game handling of the joystick so it should be more playable.

**Comment by soiaf** [comment]
Issue resolved
